Config({
    "network-name": "توشكا" ,
    "service-number": "777777777",
    "login-type": "user",
    "news-line": "شبكة توشكا نت تهنئكم بذكرى المولد النبوي * اللهم صل  و سلم على محمد و آله و ارزقنا حسن إتباعه",
    "news-line2": "",
    "input-type": "tel",
    "input-autocomplete": "on",
    "input-rm-white-spaces": 1,
    "input-to-lower": 0,
    "input-to-upper": 0,
    "input-to-arabic-numbers": 1,
    "input-only-numbers": 0,
    "input-no-numbers": 0,
    "input-only-alphanumeric": 0,
    "input-to-text-type-when": 0,
    "enable-hot-cookie": 1,
    "enable-hot-blocker": 1,
    "clear-router-cookie": 1,
    "clear-hot-cookie": 1,
    "block-time": 2,
    "try-count": 5,
    "warn-when": 3,
    "warn-message": "تحذير !! عدد محاولاتك الخاطئة اصبح {{tryCounter}} محاولات, عدد المحاولات المسموح بها هي {{tryCount}} محاولات فقط, عدد محاولاتك المتبقية {{restTryCount}} محاولات, سيتم حظرك لمدة {{blockTime}} دقائق اذا تجاوزت العدد المسموح للمحاولات",
    "price-button": true,
    "sell-point-button": true,
    "app-store-status-button": false,
    "show-date-field": true,
    "loan-button": false,
    "redirect-to-esterahah": "",// orWithProtocol: ex, https://google.com leave it blank if dont need esterahah button
    "redirect-to-mobasher": "",// orWithProtocol: ex, https://google.com leave it blank if dont need mobasher button
    "app-store-base-url": "",// orWithProtocol: ex, http://192.168.10.10/app/ // leave it blank if locally
    "profiles": [
        {
            "price": "100 ريال",
            "time": "3 ساعات",
            "transfer": "180 ميجا",
            "validity": "2 ايام",
        },
        {
            "price": "150 ريال",
            "time": "5 ساعات",
            "transfer": "250 ميجا",
            "validity": "4 ايام",
        },
        {
            "price": "250 ريال",
            "time": "3 ساعات",
            "transfer": "650 ميجا",
            "validity": "7 ايام",
        },
        {
            "price": "500 ريال",
            "time": "25 ساعة",
            "transfer": "1400 ميجا",
            "validity": "15 يوم",
        },
        {
            "price": "1000 ريال",
            "time": "60 ساعة",
            "transfer": "3000 ميجا",
            "validity": "30 يوم",
        },
        {
            "price": "5000 ريال",
            "time": "شهر ",
            "transfer": "13 جيجا",
            "validity": "30 يوم",
        },
        {
        },
    ],
    "sell-points": [
        {"name":" سوبر ماركت المستباني للمواد الغذائية والكماليات-المخرط سابقا امام مطعم الخير"},
        {"name":" المستباني للهواتف الذكية ومستلزماتها ولأأكترونيات-المخرط سابقا امام مطعم الخير "},
        {"name":" سوبر ماركت احمد عيدة مستباني مبنى المحكمة "},
        {"name":" عبد السلام قمري للمواد الغذائية والكماليات   "},
        {"name":" البحرين-يحيى خمج  "},
        {"name":"المعجمي للاكترونيات والهواتف الذكية امام المقوات"},
        {"name":" احمد علي الخميسي للمواد الغذائية والكماليات-امام مركز الرأفة   "},
        {"name":" محمد قمري للدراجات النارية وقطع غيارها "},
        {"name":" الخدري للأكترونيات وخدمات الطاقة "},
        {"name":" ناصر خميسي للأكترونيات ومستلزماتها امام محطة العبيدي للغاز "},
        {"name":"  بقالةعبدالله داحش بجانب عبد الراق خميسي للملابس "},
        {"name":" ناجي مستباني "},
        {"name":" وسيم خميسي مقابل صادق علم  "},
        
    ]
})
